### ISSUE TITLE
[EB|#LOG:EXITBS:START]

### ISSUE THREAD

**Issue by H3LLC47** [huyhoang8398/x1c7-hackintosh-20R1#1]
I am cross linking the issue I posted over here: https://github.com/aidanchandra/x1c7-hackintosh/issues/25
Perhaps you can help me with this issue? I have tried your EFI folder and the bar progresses but ultimately still gets stuck at[EB|#LOG:EXITBS:START].

**Comment by H3LLC47** [comment]
I am on BIOS 1.38

**Comment by huyhoang8398** [comment]
which EFI build did you  use in my repo? you clone the repo or you download the release build?

**Comment by H3LLC47** [comment]
I downloaded your latest release. From Jun 6th.

**Comment by huyhoang8398** [comment]
Could you try this version 
https://github.com/huyhoang8398/x1c7-hackintosh-20R1/releases/tag/v1.0.0

Also your bios is quite new that im afraid it will be compatible

**Comment by H3LLC47** [comment]
Ok, I will try and report back.

**Comment by H3LLC47** [comment]
It is still presenting the same issue. Here is the full dump of the log. Any ideas?

`00:000 00:000 AAPL: [EB|#LOG:INIT] 2021-12-21T13:01:15
00:063 00:063 AAPL: [EB|#VERSION] bootbase.efi 422.100.16~14 (Official), built 2020-02-29T16:54:28-0800
00:176 00:112 AAPL: [EB|#BUILD] BUILD-INFO[310]:{"DisplayName":"bootbase.efi","DisplayVersion":"422.100.16~14","RecordUuid":"0D6170BC-EA81-4EE7-B3B5-1D6A5DDB253B","BuildTime":"2020-02-29T16:54:28-0800","ProjectName":"efiboot","ProductName":"bootbase.efi","SourceVersion":"422.100.16","BuildVersion":"14","BuildConfiguration":"Release","BuildType":"Official"}
00:224 00:047 AAPL: [EB|`H:IS] Err(0xE) @ GV boot-signature
00:271 00:047 AAPL: [EB|`H:IS] Err(0xE) @ GV boot-image-key
00:319 00:047 AAPL: [EB|#H:IS] 0
00:393 00:073 AAPL: [EB|#WL:MODE] 0
00:438 00:045 AAPL: [EB|#CONFIG:SRC] <default>
00:483 00:045 AAPL: [EB|#CONFIG| 0] boot-save-log : 0x0000000000000002 (0x0000000000000002 < 0xFFFFFFFFFFFFFFFF) <default>
00:529 00:045 AAPL: [EB|#CONFIG| 1] wake-save-log : 0x0000000000000002 (0x0000000000000002 < 0x0000000000000002) <default>
00:574 00:045 AAPL: [EB|#CONFIG| 2] console       : 0x0000000000000001 (0x0000000000000001 < 0x0000000000000001) <default>
00:694 00:119 AAPL: [EB|#CONFIG| 3] serial        : 0x0000000000000000 (0x0000000000000000 < 0x0000000000000000) <default>
00:754 00:060 AAPL: [EB|#CONFIG| 4] embed-log-dt  : 0x0000000000000000 (0x0000000000000000 < 0x0000000000000000) <default>
00:806 00:052 AAPL: [EB|#CONFIG| 5] timestamps    : 0x0000000000000000 (0x0000000000000000 < 0xFFFFFFFFFFFFFFFF) <default>
00:853 00:047 AAPL: [EB|#CONFIG| 6] log-level     : 0x0000000000000001 (0x0000000000000001 & 0x0000000000000001) <default>
00:901 00:047 AAPL: [EB|#CONFIG| 7] breakpoint    : 0x0000000000000000 (0x0000000000000000 & 0x0000000000000000) <default>
00:948 00:047 AAPL: [EB|#CONFIG| 8] kc-read-size  : 0x0000000000100000 (0x0000000000100000 < 0xFFFFFFFFFFFFFFFF) <default>
01:018 00:070 AAPL: [EB|#WL|0] 0x01 0x01   0 0x00
01:074 00:055 AAPL: [EB|#BRD:NV] Mac-E7203C0F68AA0004
01:122 00:047 AAPL: [EB|#WL|1] 0x01 0x01   2 0x00
01:230 00:108 AAPL: [EB|`BST:IDT] {
01:286 00:055 AAPL: [EB|`BST:IDT] }
01:346 00:060 AAPL: [EB|#WL|2] 0x01 0x01   3 0x00
01:409 00:062 AAPL: [EB|#WL|3] 0x01 0x01   4 0x00
01:467 00:058 AAPL: [EB|#BRD:NV] Mac-E7203C0F68AA0004
01:521 00:054 AAPL: [EB|#WL|4] 0x01 0x01   5 0x00
01:569 00:047 AAPL: [EB|`H:CHK] BM: 0x0000000000000000
01:617 00:048 AAPL: [EB|`H:CHK] Err(0xE) @ GV boot-signature
01:683 00:065 AAPL: [EB|#WL|5] 0x01 0x01  23 0x0E
01:731 00:047 AAPL: [EB|`H:CPM] Err(0xE), (24, 24) @ GV Persistent-memory-note
01:847 00:116 AAPL: [EB|#SB:P] 0x1
01:895 00:047 AAPL: [EB|`B:MN] BM: +SB
01:943 00:047 AAPL: [EB|#LIMG:DP] Acpi(PNP0A03,0)/Pci(14|0)/Usb(2, 0)/HD(Part2,SigEAF227C1-FA7D-4A21-8333-82DCFF1FDC3F)
02:003 00:060 AAPL: [EB|#LIMG:FP] \System\Library\CoreServices\boot.efi
02:066 00:062 AAPL: [EB|#LIMG:OPT] ()
02:124 00:058 AAPL: [EB|#RPS] R?0 P?0 S?0
02:183 00:058 AAPL: [EB|`OPT:LXF] 'LF (\\System\\Library\\CoreServices\\com.apple.Boot.plist)
02:231 00:048 AAPL: [EB|`LD:LF] FIO: 0, DIR: 1, P: \\System\\Library\\CoreServices\\com.apple.Boot.plist, DP: 0
02:279 00:047 AAPL: [EB|`LD:OFS] Err(0xE) @ OPEN (\\System\\Library\\CoreServices\\com.apple.Boot.plist)
02:398 00:118 AAPL: [EB|`OPT:LXF] Err(0xE) @ 'LF
02:445 00:047 AAPL: [EB|`OPT:LXF] 'LF (Library\\Preferences\\SystemConfiguration\\com.apple.Boot.plist)
02:493 00:047 AAPL: [EB|`LD:LF] FIO: 0, DIR: 1, P: Library\\Preferences\\SystemConfiguration\\com.apple.Boot.plist, DP: 0
02:542 00:049 AAPL: [EB:#KF] (root-dmg=file:///Install%20macOS%20Catalina.app/Contents/SharedSupport/BaseSystem.dmg)
02:590 00:047 AAPL: [EB|#MBA:CL] ()
02:647 00:056 AAPL: [EB|#MBA:NV] (keepsyms=1 debug=0x100)
02:710 00:063 AAPL: [EB|#MBA:KF] (root-dmg=file:///Install%20macOS%20Catalina.app/Contents/SharedSupport/BaseSystem.dmg)
02:758 00:047 AAPL: [EB|#MBA:OUT] (keepsyms=1 debug=0x100 root-dmg=file:///Install%20macOS%20Catalina.app/Contents/SharedSupport/BaseSystem.dmg chunklist-security-epoch=0 -chunklist-no-rev2-dev)
02:806 00:047 AAPL: [EB|#OPT:BM] 0x204080
02:921 00:115 AAPL: [EB|`OPT:LXF] 'LF (\\System\\Library\\CoreServices\\PlatformSupport.plist)
02:969 00:047 AAPL: [EB|`LD:LF] FIO: 0, DIR: 1, P: \\System\\Library\\CoreServices\\PlatformSupport.plist, DP: 0
03:040 00:070 AAPL: [EB|#B:VAw]
03:093 00:052 AAPL: [EB|`P:DCCPR] Err(0xE) @ GV AAPL,CoProcessorReboot
03:140 00:047 AAPL: [EB|#P:PI0]
03:213 00:073 AAPL: [EB|#P:SLOT] 3
03:357 00:143 AAPL: [EB|#P:SKIP.3]
03:411 00:054 AAPL: [EB|`CS:CSKSD] {
03:459 00:048 AAPL: [EB|`CS:CSKSD] Err(0xE) @ GV 8D63D4FE-BD3C-4AAD-881D-86FD974BC1DF:boot-info-payload
03:569 00:109 AAPL: [EB|`G:CS] } Ok(0)
03:723 00:153 AAPL: [EB|`LD:LF] FIO: 0, DIR: 1, P: <null string>, DP: 1
03:996 00:272 AAPL: [EB|`B:SBS] SZ: 617016
04:053 00:056 AAPL: [EB|#B:SHA] fe9e48a334db5bca8b8d8f3d0aa3f18b7dc5ad24
04:160 00:106 AAPL: [EB|`WL:PWLFNV] Err(0xE) @ GV wake-failure
04:207 00:047 AAPL: [EB|`WL:DT] Err(0xE) @ WL:PWLFNV
04:255 00:047 AAPL: [EB|#WL:DT] 0x53 0x42  83 0x48
04:302 00:047 AAPL: [EB|`LD:LKC] SB -> (System\Library\PrelinkedKernels\immutablekernel)
04:370 00:067 AAPL: [EB|`LD:LKC] BPDK -> (System\Library\PrelinkedKernels\immutablekernel.development)
04:480 00:110 AAPL: [EB|`LD:LF] FIO: 0, DIR: 1, P: System\\Library\\PrelinkedKernels\\immutablekernel.development, DP: 0
04:539 00:059 AAPL: [EB|`LD:OFS] Err(0xE) @ OPEN (System\\Library\\PrelinkedKernels\\immutablekernel.development)
04:590 00:051 AAPL: [EB|`LD:LKC] BPDK,!R -> (System\Library\PrelinkedKernels\immutablekernel)
04:636 00:045 AAPL: [EB|`LD:LF] FIO: 0, DIR: 1, P: System\\Library\\PrelinkedKernels\\immutablekernel, DP: 0
27:672 23:035 OC: Prelinked injection AirportItlwm.kext () - Invalid Parameter
29:752 02:080 AAPL: [EB|#SB:HW] j137ap\0
29:801 00:048 AAPL: [EB|#SB:MF] (System\\Library\\PrelinkedKernels\\immutablekernel.j137ap.im4m)
29:848 00:047 AAPL: [EB|`LD:LF] FIO: 0, DIR: 1, P: System\\Library\\PrelinkedKernels\\immutablekernel.j137ap.im4m, DP: 0
30:884 01:035 AAPL: [EB|#SB:MKRN]
30:955 00:070 AAPL: [EB|`LD:LKFS] } Ok(0)
31:091 00:135 AAPL: [EB|`LD:LKC] } Ok(0)
31:143 00:052 AAPL: [EB|#FWFM] 0xFFFFFF7F
31:191 00:047 AAPL: [EB|#FWFT] 0xFDAFF066
31:239 00:047 AAPL: [EB|#CSR:IN] 0x00000040
31:286 00:047 AAPL: [EB|#CSR:OUT] 0x00000040
31:336 00:049 AAPL: [EB|`BST:FBS] {
31:407 00:070 AAPL: [EB|`BST:FBS] BA.ADSZ: 0
31:464 00:056 AAPL: [EB|`BST:FBS] BA.KSDSZ: 0
31:511 00:047 AAPL: [EB|`B:WFDW] Err(0xE), 0 @ LocHB 71B4903C-14EC-42C4-BDC6-CE1449930E49
31:631 00:119 AAPL: [EB|#LOG:DT] 2021-12-21T13:01:47
31:688 00:056 AAPL: [EB|#LOG:EXITBS:START] 2021-12-21T13:01:47
`

**Comment by H3LLC47** [comment]
According to this post, I can roll back to an older BIOS. What version are you running? 
[https://forums.lenovo.com/t5/ThinkPad-X-Series-Laptops/Bios-1-29-on-X1-Carbon-Gen7-rollback/m-p/5004072?page=1#5013221](url)

**Comment by H3LLC47** [comment]
Was able to fix the issue by using the newest EFI folder and editing the plist CPU data, enabling verbose mode and just today I had a thought that it could be hardware related because I always saw NVMEIO errors, so I swapped my SKHynix 1TB drive for a Micron 512GB drive and the installer booted perfectly.

**Comment by huyhoang8398** [comment]
Great, sorry for late reply, Merry Christmas
Thanks for using my EFI, I will note your issue and update my docs

**Comment by H3LLC47** [comment]
> Great, sorry for late reply, Merry Christmas
> Thanks for using my EFI, I will note your issue and update my docs

Thanks, I also made my own fork for people with my specific model of x1 carbon 7th gen. I appreciate the help.
